import { colours, weddingTemplate } from './template';
import type { FontId, PlaqueDesign, ValidationResult } from './types';
const glyphWidthFactors:Record<FontId,number>={elegant:.53,modern:.58};
export function normalizedText(value:string){return value.trim().replace(/\s+/g,' ');}
export function fitText(value:string,field:'names'|'date',font:FontId){const constraint=weddingTemplate.fields[field];const text=normalizedText(value)||(field==='names'?'Names':'Event date');const weightedLength=[...text].reduce((total,character)=>{if("ilI1.,' ".includes(character))return total+.38;if('MW@&'.includes(character))return total+1.15;return total+1;},0);const estimated=weightedLength*constraint.maxFontSizeMm*glyphWidthFactors[font];if(estimated<=constraint.maxWidthMm)return constraint.maxFontSizeMm;return Math.max(constraint.minFontSizeMm,Number((constraint.maxFontSizeMm*constraint.maxWidthMm/estimated).toFixed(2)));}
export function fitTextWithMetrics(value:string,field:'names'|'date',font:FontId,measure:(text:string,size:number)=>number){const text=normalizedText(value)||(field==='names'?'Names':'Event date');const fallback=fitText(text,field,font);const constraint=weddingTemplate.fields[field];const width=measure(text,fallback);if(width<=constraint.maxWidthMm)return fallback;return Math.max(constraint.minFontSizeMm,Number((fallback*constraint.maxWidthMm/width).toFixed(2)));}
export function validateDesign(design:PlaqueDesign):ValidationResult{const errors:ValidationResult['errors']={};const names=normalizedText(design.names);const date=normalizedText(design.date);if(!names)errors.names='Enter at least one name.';else if([...names].length>weddingTemplate.fields.names.maxCharacters)errors.names=`Use ${weddingTemplate.fields.names.maxCharacters} characters or fewer.`;if(!date)errors.date='Enter the event date.';else if([...date].length>weddingTemplate.fields.date.maxCharacters)errors.date=`Use ${weddingTemplate.fields.date.maxCharacters} characters or fewer.`;if(!colours[design.baseColour]||!colours[design.detailColour])errors.colours='Select supported colours.';else if(colours[design.baseColour].value===colours[design.detailColour].value)errors.colours='Choose contrasting plaque and detail colours.';return{valid:Object.keys(errors).length===0,errors};}
export function parseDesign(value:unknown):PlaqueDesign{if(!value||typeof value!=='object')throw new Error('The design file is not valid JSON data.');const candidate=value as Partial<PlaqueDesign>;if(candidate.version!==1||candidate.templateId!==weddingTemplate.id)throw new Error('This design version or template is not supported.');if(typeof candidate.names!=='string'||typeof candidate.date!=='string')throw new Error('The design is missing editable text.');if(candidate.font!=='elegant'&&candidate.font!=='modern')throw new Error('The design uses an unsupported font.');if(!candidate.baseColour||!candidate.detailColour||!colours[candidate.baseColour]||!colours[candidate.detailColour])throw new Error('The design uses unsupported colours.');const design=candidate as PlaqueDesign;const validation=validateDesign(design);if(!validation.valid)throw new Error(Object.values(validation.errors)[0]);return design;}

