import { colours, defaultDesign, getTemplate, isEligible, weddingTemplates } from './template';
import type { FontId, PlaqueDesign, TemplateId, ValidationResult } from './types';
const glyphWidthFactors:Record<FontId,number>={elegant:.53,modern:.58};
export function normalizedText(value:string){return value.trim().replace(/\s+/g,' ');}
export function fitText(value:string,field:'names'|'date',font:FontId,templateId:TemplateId='wedding-classic-v1'){const constraint=getTemplate(templateId).fields[field];const text=normalizedText(value)||(field==='names'?'Names':'Event date');const weighted=[...text].reduce((total,character)=>"ilI1.,' ".includes(character)?total+.38:'MW@&'.includes(character)?total+1.15:total+1,0);const estimate=weighted*constraint.maxFontSizeMm*glyphWidthFactors[font];return estimate<=constraint.maxWidthMm?constraint.maxFontSizeMm:Math.max(constraint.minFontSizeMm,Number((constraint.maxFontSizeMm*constraint.maxWidthMm/estimate).toFixed(2)));}
export function fitTextWithMetrics(value:string,field:'names'|'date',font:FontId,measure:(text:string,size:number)=>number,templateId:TemplateId='wedding-classic-v1'){const text=normalizedText(value)||(field==='names'?'Names':'Event date');const fallback=fitText(text,field,font,templateId);const constraint=getTemplate(templateId).fields[field];const width=measure(text,fallback);return width<=constraint.maxWidthMm?fallback:Math.max(constraint.minFontSizeMm,Number((fallback*constraint.maxWidthMm/width).toFixed(2)));}
export function deriveMonogram(names:string){const parts=normalizedText(names).split(/\s*(?:&|\+|\band\b|\bet\b)\s*/i).filter(Boolean);return parts.slice(0,2).map((part)=>[...part.trim()][0]?.toUpperCase()??'').join('')||'M';}
export function validateDesign(design:PlaqueDesign):ValidationResult{const errors:ValidationResult['errors']={};const template=getTemplate(design.templateId);const names=normalizedText(design.names);const date=normalizedText(design.date);if(!names)errors.names='Enter at least one name.';else if([...names].length>template.fields.names.maxCharacters)errors.names=`Use ${template.fields.names.maxCharacters} characters or fewer.`;if(!date)errors.date='Enter the event date.';else if([...date].length>template.fields.date.maxCharacters)errors.date=`Use ${template.fields.date.maxCharacters} characters or fewer.`;if(!colours[design.baseColour]||!colours[design.detailColour])errors.colours='Select supported colours.';else if(colours[design.baseColour].value===colours[design.detailColour].value)errors.colours='Choose contrasting plaque and detail colours.';if(!isEligible(design))errors.elements='This combination is not available for the selected template.';return{valid:Object.keys(errors).length===0,errors};}
export function parseDesign(value:unknown):PlaqueDesign{if(!value||typeof value!=='object')throw new Error('The design file is not valid JSON data.');const candidate=value as Partial<PlaqueDesign>;if(candidate.version!==1||!candidate.templateId||!weddingTemplates[candidate.templateId])throw new Error('This design version or template is not supported.');if(typeof candidate.names!=='string'||typeof candidate.date!=='string')throw new Error('The design is missing editable text.');if(candidate.font!=='elegant'&&candidate.font!=='modern')throw new Error('The design uses an unsupported font.');if(!candidate.baseColour||!candidate.detailColour||!colours[candidate.baseColour]||!colours[candidate.detailColour])throw new Error('The design uses unsupported colours.');const template=getTemplate(candidate.templateId);const design:PlaqueDesign={...defaultDesign,...candidate,ornament:candidate.ornament??template.defaults.ornament,border:candidate.border??template.defaults.border} as PlaqueDesign;const validation=validateDesign(design);if(!validation.valid)throw new Error(Object.values(validation.errors)[0]);return design;}
