import { useEffect, useState } from 'react';
import type { Font } from 'opentype.js';
import { heartSvgPoints } from './decorations';
import { loadProductionFont } from './fontMetrics';
import { fitText, fitTextWithMetrics, normalizedText } from './layout';
import { colours, weddingTemplate } from './template';
import type { PlaqueDesign } from './types';
export function PlaquePreview({design}:{design:PlaqueDesign}){const[font,setFont]=useState<Font|null>(null);useEffect(()=>{let active=true;setFont(null);loadProductionFont(design.font).then((loaded)=>{if(active)setFont(loaded);}).catch(()=>setFont(null));return()=>{active=false;};},[design.font]);const names=normalizedText(design.names)||'Names';const date=normalizedText(design.date)||'Event date';const size=(text:string,field:'names'|'date')=>font?fitTextWithMetrics(text,field,design.font,(value,fontSize)=>font.getAdvanceWidth(value,fontSize,{kerning:true})):fitText(text,field,design.font);const namesSize=size(names,'names');const dateSize=size(date,'date');const detail=colours[design.detailColour].value;const base=colours[design.baseColour].value;const fontFamily=design.font==='elegant'?'Lobster, cursive':'Montserrat, sans-serif';const fontWeight=design.font==='modern'?600:400;return <figure className="preview-frame" aria-label="Live plaque preview"><div className="preview-stage"><svg className="plaque" viewBox="0 0 120 70" role="img" aria-labelledby="preview-title preview-description"><title id="preview-title">Personalized wedding plaque</title><desc id="preview-description">A 120 by 70 millimetre plaque showing {names} and {date}.</desc><defs><filter id="raised" x="-20%" y="-20%" width="140%" height="150%"><feDropShadow dx="0.45" dy="0.75" stdDeviation="0.45" floodColor="#000" floodOpacity="0.7"/><feDropShadow dx="-0.2" dy="-0.25" stdDeviation="0.18" floodColor="#fff" floodOpacity="0.28"/></filter></defs><rect width="120" height="70" rx="4" fill={base}/><g fill={detail} stroke={detail} filter="url(#raised)"><text x="60" y="27" textAnchor="middle" fontFamily={fontFamily} fontWeight={fontWeight} fontSize={namesSize} stroke="none">{names}</text><line x1="24" y1="39" x2="51" y2="39" strokeWidth="0.8" strokeLinecap="round"/><line x1="69" y1="39" x2="96" y2="39" strokeWidth="0.8" strokeLinecap="round"/><polygon points={heartSvgPoints} stroke="none"/><text x="60" y="55" textAnchor="middle" fontFamily={fontFamily} fontWeight={fontWeight} fontSize={dateSize} stroke="none">{date}</text></g><rect x="8" y="8" width="104" height="54" rx="1.5" fill="none" stroke="rgba(255,255,255,.15)" strokeWidth="0.25" strokeDasharray="1.2 1.2" className="safe-area"/></svg></div><figcaption><span>{weddingTemplate.widthMm} × {weddingTemplate.heightMm} mm</span><span>{weddingTemplate.baseThicknessMm} mm base + {weddingTemplate.detailHeightMm} mm detail</span></figcaption></figure>;}

