import type { BorderId, ColourId, OrnamentId, PlaqueDesign, PlaqueTemplate, TemplateId } from './types';
const physical={widthMm:120,heightMm:70,baseThicknessMm:2,detailHeightMm:1,safeMarginMm:8};
export const weddingTemplates:Record<TemplateId,PlaqueTemplate>={
  'wedding-classic-v1':{...physical,id:'wedding-classic-v1',title:'Heritage romance',subtitle:'Timeless & ceremonial',description:'Formal names, a fine divider and a quiet date line inspired by engraved stationery.',layout:'classic',fields:{names:{x:60,baselineY:26,maxCharacters:30,minFontSizeMm:5.5,maxFontSizeMm:11.5,maxWidthMm:92,align:'center'},date:{x:60,baselineY:54,maxCharacters:30,minFontSizeMm:3.2,maxFontSizeMm:5,maxWidthMm:72,align:'center'}},eligibility:{fonts:['alex-brush','parisienne','cormorant','playfair','baskerville','elegant'],ornaments:['heart','rings','stars'],borders:['none','single']},defaults:{font:'alex-brush',ornament:'rings',border:'none'}},
  'wedding-botanical-v1':{...physical,id:'wedding-botanical-v1',title:'Botanical crest',subtitle:'Organic & graceful',description:'An airy serif inscription held by delicate foliage in opposite corners.',layout:'botanical',fields:{names:{x:60,baselineY:31,maxCharacters:27,minFontSizeMm:5,maxFontSizeMm:10.5,maxWidthMm:72,align:'center'},date:{x:60,baselineY:46,maxCharacters:25,minFontSizeMm:3.2,maxFontSizeMm:4.8,maxWidthMm:60,align:'center'}},eligibility:{fonts:['cormorant','playfair','baskerville','allura','parisienne','alex-brush'],ornaments:['botanical','heart','none'],borders:['none','single']},defaults:{font:'cormorant',ornament:'botanical',border:'none'}},
  'wedding-modern-v1':{...physical,id:'wedding-modern-v1',title:'Editorial modern',subtitle:'Bold & architectural',description:'Editorial typography balanced by a compact graphic mark and generous space.',layout:'modern',fields:{names:{x:18,baselineY:31,maxCharacters:27,minFontSizeMm:4,maxFontSizeMm:8,maxWidthMm:66,align:'left'},date:{x:18,baselineY:44,maxCharacters:24,minFontSizeMm:3,maxFontSizeMm:4.2,maxWidthMm:56,align:'left'}},eligibility:{fonts:['bodoni','modern','cinzel','playfair'],ornaments:['none','rings','stars'],borders:['single','double']},defaults:{font:'bodoni',ornament:'stars',border:'single'}},
  'wedding-monogram-v1':{...physical,id:'wedding-monogram-v1',title:'Signature monogram',subtitle:'Personal & distinctive',description:'Large initials and a restrained inscription share a formal split composition.',layout:'monogram',fields:{names:{x:52,baselineY:30,maxCharacters:23,minFontSizeMm:4.2,maxFontSizeMm:7,maxWidthMm:58,align:'left'},date:{x:52,baselineY:43,maxCharacters:22,minFontSizeMm:3,maxFontSizeMm:4.2,maxWidthMm:48,align:'left'}},eligibility:{fonts:['cinzel','cormorant','playfair','bodoni','baskerville','alex-brush'],ornaments:['none','heart','stars'],borders:['none','single','double']},defaults:{font:'cinzel',ornament:'heart',border:'single'}},
};
export const weddingTemplate=weddingTemplates['wedding-classic-v1'];
export const getTemplate=(id:TemplateId)=>weddingTemplates[id];
export const templateList=Object.values(weddingTemplates);
export const defaultDesign:PlaqueDesign={version:1,templateId:weddingTemplate.id,names:'Camille & Morgan',date:'11 April 2026',font:'alex-brush',ornament:'rings',border:'none',baseColour:'charcoal',detailColour:'gold'};
export const colours:Record<ColourId,{label:string;value:string;role:'base'|'detail'|'both'}>={charcoal:{label:'Charcoal',value:'#171717',role:'base'},ivory:{label:'Ivory',value:'#eee7d8',role:'both'},navy:{label:'Midnight navy',value:'#142535',role:'base'},sage:{label:'Sage',value:'#829072',role:'both'},gold:{label:'Warm gold',value:'#c99a4b',role:'detail'},silver:{label:'Soft silver',value:'#bfc1c2',role:'detail'}};
export const ornaments:Record<OrnamentId,string>={heart:'Heart',rings:'Wedding rings',stars:'Stars',botanical:'Leaf sprigs',none:'No ornament'};
export const borders:Record<BorderId,string>={none:'No border',single:'Fine border',double:'Double border'};
export const baseColours=(Object.keys(colours) as ColourId[]).filter((id)=>colours[id].role!=='detail');
export const detailColours=(Object.keys(colours) as ColourId[]).filter((id)=>colours[id].role!=='base');
export function designForTemplate(current:PlaqueDesign,templateId:TemplateId):PlaqueDesign{const template=getTemplate(templateId);return{...current,templateId,font:template.eligibility.fonts.includes(current.font)?current.font:template.defaults.font,ornament:template.eligibility.ornaments.includes(current.ornament)?current.ornament:template.defaults.ornament,border:template.eligibility.borders.includes(current.border)?current.border:template.defaults.border};}
export function isEligible(design:PlaqueDesign){const template=getTemplate(design.templateId);return template.eligibility.fonts.includes(design.font)&&template.eligibility.ornaments.includes(design.ornament)&&template.eligibility.borders.includes(design.border);}
