import type { BorderId, ColourId, OrnamentId, PlaqueDesign, PlaqueTemplate, TemplateId } from './types';
const physical={widthMm:120,heightMm:70,baseThicknessMm:2,detailHeightMm:1,safeMarginMm:8};
export const weddingTemplates:Record<TemplateId,PlaqueTemplate>={
  'wedding-classic-v1':{...physical,id:'wedding-classic-v1',title:'Classic heart',subtitle:'Timeless & romantic',description:'Centered script, a delicate divider and a small celebratory symbol.',layout:'classic',fields:{names:{x:60,baselineY:27,maxCharacters:30,minFontSizeMm:6,maxFontSizeMm:12,maxWidthMm:100},date:{x:60,baselineY:55,maxCharacters:30,minFontSizeMm:3.2,maxFontSizeMm:5.5,maxWidthMm:76}},eligibility:{fonts:['elegant','modern'],ornaments:['heart','rings','stars'],borders:['none','single']},defaults:{font:'elegant',ornament:'heart',border:'none'}},
  'wedding-botanical-v1':{...physical,id:'wedding-botanical-v1',title:'Botanical',subtitle:'Organic & graceful',description:'A soft names layout framed by balanced leafy sprigs.',layout:'botanical',fields:{names:{x:60,baselineY:32,maxCharacters:30,minFontSizeMm:6,maxFontSizeMm:11,maxWidthMm:84},date:{x:60,baselineY:47,maxCharacters:30,minFontSizeMm:3.2,maxFontSizeMm:5,maxWidthMm:64}},eligibility:{fonts:['elegant','modern'],ornaments:['botanical','heart','none'],borders:['none','single']},defaults:{font:'elegant',ornament:'botanical',border:'none'}},
  'wedding-modern-v1':{...physical,id:'wedding-modern-v1',title:'Modern frame',subtitle:'Clean & architectural',description:'Strong typography, generous spacing and a precise linear border.',layout:'modern',fields:{names:{x:60,baselineY:31,maxCharacters:30,minFontSizeMm:5.5,maxFontSizeMm:9,maxWidthMm:92},date:{x:60,baselineY:46,maxCharacters:30,minFontSizeMm:3.2,maxFontSizeMm:4.8,maxWidthMm:72}},eligibility:{fonts:['modern'],ornaments:['none','rings','stars'],borders:['single','double']},defaults:{font:'modern',ornament:'none',border:'single'}},
  'wedding-monogram-v1':{...physical,id:'wedding-monogram-v1',title:'Monogram',subtitle:'Personal & distinctive',description:'A large derived monogram anchors the names and date.',layout:'monogram',fields:{names:{x:60,baselineY:44,maxCharacters:30,minFontSizeMm:4.8,maxFontSizeMm:7.5,maxWidthMm:88},date:{x:60,baselineY:56,maxCharacters:30,minFontSizeMm:3,maxFontSizeMm:4.5,maxWidthMm:68}},eligibility:{fonts:['elegant','modern'],ornaments:['none','heart','stars'],borders:['none','single','double']},defaults:{font:'elegant',ornament:'none',border:'single'}},
};
export const weddingTemplate=weddingTemplates['wedding-classic-v1'];
export const getTemplate=(id:TemplateId)=>weddingTemplates[id];
export const templateList=Object.values(weddingTemplates);
export const defaultDesign:PlaqueDesign={version:1,templateId:weddingTemplate.id,names:'Camille & Morgan',date:'11 April 2026',font:'elegant',ornament:'heart',border:'none',baseColour:'charcoal',detailColour:'gold'};
export const colours:Record<ColourId,{label:string;value:string;role:'base'|'detail'|'both'}>={charcoal:{label:'Charcoal',value:'#171717',role:'base'},ivory:{label:'Ivory',value:'#eee7d8',role:'both'},navy:{label:'Midnight navy',value:'#142535',role:'base'},sage:{label:'Sage',value:'#829072',role:'both'},gold:{label:'Warm gold',value:'#c99a4b',role:'detail'},silver:{label:'Soft silver',value:'#bfc1c2',role:'detail'}};
export const ornaments:Record<OrnamentId,string>={heart:'Heart',rings:'Wedding rings',stars:'Stars',botanical:'Leaf sprigs',none:'No ornament'};
export const borders:Record<BorderId,string>={none:'No border',single:'Fine border',double:'Double border'};
export const baseColours=(Object.keys(colours) as ColourId[]).filter((id)=>colours[id].role!=='detail');
export const detailColours=(Object.keys(colours) as ColourId[]).filter((id)=>colours[id].role!=='base');
export function designForTemplate(current:PlaqueDesign,templateId:TemplateId):PlaqueDesign{const template=getTemplate(templateId);return{...current,templateId,font:template.eligibility.fonts.includes(current.font)?current.font:template.defaults.font,ornament:template.eligibility.ornaments.includes(current.ornament)?current.ornament:template.defaults.ornament,border:template.eligibility.borders.includes(current.border)?current.border:template.defaults.border};}
export function isEligible(design:PlaqueDesign){const template=getTemplate(design.templateId);return template.eligibility.fonts.includes(design.font)&&template.eligibility.ornaments.includes(design.ornament)&&template.eligibility.borders.includes(design.border);}
